//! Real RFC-9420 TreeKEM group encryption, wrapping `saorsa_mls::TreeKemGroup`.
//!
//! Unlike the legacy GSS plane in [`crate::mls::group`] (a per-epoch shared
//! secret with no forward secrecy / no post-compromise security), this plane
//! provides genuine **forward secrecy** and **post-compromise security** via a
//! KEM-keypair-per-node ratchet tree, UpdatePath/Commit distribution, and
//! init→commit→epoch key-schedule chaining. New `MlsEncrypted` groups use this
//! plane (ADR-0012).
//!
//! ## Boundary
//!
//! The daemon talks to this wrapper in **bytes**, not `saorsa_mls` types:
//! `Commit`s, `Welcome`s, key packages, and ciphertexts all cross the wrapper
//! boundary as postcard-encoded `Vec<u8>` so the rest of x0x never depends on
//! the upstream wire types directly.
//!
//! ## Identity (Phase 1/2 scope)
//!
//! Each member is represented by a `saorsa_mls::MemberIdentity` whose `MemberId`
//! is bridged deterministically from the x0x [`AgentId`] (first 16 bytes). The
//! identity's *signing/KEM* keys are generated by saorsa-mls and are **not yet**
//! tied to the agent's long-term `AgentKeypair` — that, plus persisting the
//! identity across restarts, is tracked for Phase 2/4 (see ADR-0012). For now a
//! group and its members are session-scoped, matching the pre-existing
//! `/mls/groups` behaviour while making the crypto real.

use crate::identity::AgentId;
use crate::mls::{MlsError, Result};
use saorsa_mls::{
    treekem_group::{ApplicationCiphertext, TreeKemCommit, TreeKemGroup, TreeKemWelcome},
    CipherSuite, KeyPackage, MemberId, MemberIdentity,
};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Which secure-group plane a group runs on. Persisted in group metadata so the
/// daemon can dispatch secure-content and membership operations to the right
/// implementation while GSS and TreeKEM groups coexist (ADR-0012).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TreeKemPlane {
    /// Legacy Group-Shared-Secret plane ([`crate::mls::group`]). No FS/PCS.
    Gss,
    /// Real RFC-9420 TreeKEM plane (this module). FS + PCS.
    #[default]
    TreeKem,
}

/// Deterministic bridge from an x0x [`AgentId`] (32 bytes) to a saorsa-mls
/// `MemberId` (16 bytes). Uses the first 16 bytes of the AgentId — identical to
/// the legacy wrapper's bridge so a given agent maps to a stable `MemberId`.
fn agent_id_to_member_id(agent_id: &AgentId) -> MemberId {
    let mut bytes = [0u8; 16];
    bytes.copy_from_slice(&agent_id.as_bytes()[..16]);
    MemberId::from_bytes(bytes)
}

fn encode<T: Serialize>(value: &T, what: &str) -> Result<Vec<u8>> {
    postcard::to_stdvec(value).map_err(|e| MlsError::MlsOperation(format!("encode {what}: {e}")))
}

fn decode<T: for<'de> Deserialize<'de>>(bytes: &[u8], what: &str) -> Result<T> {
    postcard::from_bytes(bytes).map_err(|e| MlsError::MlsOperation(format!("decode {what}: {e}")))
}

/// A member's freshly-minted identity plus the public key package to hand to an
/// inviter. The holder keeps the (private) identity until a `Welcome` arrives,
/// then consumes it via [`TreeKemMlsGroup::join_from_welcome`].
///
/// Carries the agent's KEM/signing **secret** key material in memory; never
/// serialize this to disk in the clear.
pub struct PreparedMember {
    agent: AgentId,
    identity: MemberIdentity,
    key_package_bytes: Vec<u8>,
}

impl PreparedMember {
    /// The serialized public `KeyPackage` to publish / hand to the inviter so
    /// they can call [`TreeKemMlsGroup::add_member`].
    #[must_use]
    pub fn key_package_bytes(&self) -> &[u8] {
        &self.key_package_bytes
    }

    /// The agent this prepared identity belongs to.
    #[must_use]
    pub fn agent(&self) -> &AgentId {
        &self.agent
    }
}

impl std::fmt::Debug for PreparedMember {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PreparedMember")
            .field("agent", &self.agent)
            .field(
                "key_package_bytes",
                &format!("{} bytes", self.key_package_bytes.len()),
            )
            .finish_non_exhaustive()
    }
}

/// Output of [`TreeKemMlsGroup::add_member`]: a `Commit` for existing members
/// and a `Welcome` for the joiner, both postcard-encoded.
#[derive(Debug, Clone)]
pub struct AddMemberOutput {
    /// Encoded [`TreeKemCommit`] — deliver to every existing member; they call
    /// [`TreeKemMlsGroup::process_commit`].
    pub commit: Vec<u8>,
    /// Encoded [`TreeKemWelcome`] — deliver to the joiner; they call
    /// [`TreeKemMlsGroup::join_from_welcome`].
    pub welcome: Vec<u8>,
}

/// A real TreeKEM group as held by one member, keyed by x0x [`AgentId`].
///
/// Restore re-supplies the member identity separately (via a [`PreparedMember`]),
/// so the live group does not retain it — see [`Self::from_snapshot_bytes`].
pub struct TreeKemMlsGroup {
    inner: TreeKemGroup,
    /// Best-effort `AgentId → leaf` map, populated from operations this instance
    /// performs (own leaf, members it adds). The named-group roster
    /// (`src/groups`) is the authoritative roster; this exists so the wrapper
    /// can resolve an agent to a leaf for [`Self::remove_member`].
    agent_to_leaf: HashMap<AgentId, u32>,
}

impl std::fmt::Debug for TreeKemMlsGroup {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("TreeKemMlsGroup")
            .field("inner", &self.inner)
            .field("members_tracked", &self.agent_to_leaf.len())
            .finish_non_exhaustive()
    }
}

impl TreeKemMlsGroup {
    /// Cipher suite used for all x0x TreeKEM groups: ML-KEM-768 + ML-DSA-65 +
    /// ChaCha20-Poly1305 (saorsa-mls SPEC-2 default, `0x0B01`).
    fn suite() -> CipherSuite {
        CipherSuite::default()
    }

    /// Create a fresh single-member group owned by `creator` (leaf 0).
    ///
    /// # Errors
    /// Returns [`MlsError`] if identity generation or group creation fails.
    pub fn create(group_id: Vec<u8>, creator: AgentId) -> Result<Self> {
        let member_id = agent_id_to_member_id(&creator);
        let identity = MemberIdentity::generate_with_suite(member_id, Self::suite())
            .map_err(|e| MlsError::Identity(format!("creator identity: {e}")))?;
        let inner = TreeKemGroup::create(group_id, identity)
            .map_err(|e| MlsError::SaorsaMls(format!("treekem create: {e}")))?;

        let mut agent_to_leaf = HashMap::new();
        if let Some(leaf) = inner.own_leaf() {
            agent_to_leaf.insert(creator, leaf);
        }
        Ok(Self {
            inner,
            agent_to_leaf,
        })
    }

    /// Mint a fresh member identity + public key package for `agent`, to be
    /// handed to a group member who will call [`Self::add_member`]. The returned
    /// [`PreparedMember`] must be retained until the `Welcome` arrives.
    ///
    /// # Errors
    /// Returns [`MlsError`] if identity generation or key-package encoding fails.
    pub fn prepare_member(agent: AgentId) -> Result<PreparedMember> {
        let member_id = agent_id_to_member_id(&agent);
        let identity = MemberIdentity::generate_with_suite(member_id, Self::suite())
            .map_err(|e| MlsError::Identity(format!("member identity: {e}")))?;
        let key_package_bytes = encode(&identity.key_package, "key package")?;
        Ok(PreparedMember {
            agent,
            identity,
            key_package_bytes,
        })
    }

    /// Add `joiner` (identified by their published key-package bytes) to the
    /// group. Returns the `Commit` for existing members and the `Welcome` for
    /// the joiner. This instance advances to the next epoch.
    ///
    /// # Errors
    /// Returns [`MlsError`] if the key package is invalid, the suite mismatches,
    /// or the TreeKEM operation fails.
    pub fn add_member(
        &mut self,
        joiner: AgentId,
        joiner_key_package: &[u8],
    ) -> Result<AddMemberOutput> {
        // Reject re-adding an agent this instance already tracks. saorsa-mls
        // does NOT dedup — `tree.add_leaf` would assign a *second* leaf to the
        // same agent, and the `agent_to_leaf` insert below would overwrite the
        // first, orphaning it (a later remove would leave the first leaf live
        // and able to decrypt). The authoritative dedup is the named-group
        // roster in `src/groups`; this guard catches the common case locally.
        if self.agent_to_leaf.contains_key(&joiner) {
            return Err(MlsError::MlsOperation(format!(
                "agent {:?} is already a member of this group",
                joiner.as_bytes()
            )));
        }
        let kp: KeyPackage = decode(joiner_key_package, "joiner key package")?;
        let (commit, welcome) = self
            .inner
            .add_member(&kp)
            .map_err(|e| MlsError::SaorsaMls(format!("treekem add_member: {e}")))?;

        // Record the joiner's leaf from the commit so we can resolve it later.
        if let Some((leaf, _)) = commit.added.first() {
            self.agent_to_leaf.insert(joiner, *leaf);
        }

        Ok(AddMemberOutput {
            commit: encode(&commit, "commit")?,
            welcome: encode(&welcome, "welcome")?,
        })
    }

    /// Join an existing group from a `Welcome`, consuming the prepared identity
    /// whose key package produced it.
    ///
    /// # Errors
    /// Returns [`MlsError`] if the welcome is malformed or fails verification.
    pub fn join_from_welcome(prepared: PreparedMember, welcome: &[u8]) -> Result<Self> {
        let welcome: TreeKemWelcome = decode(welcome, "welcome")?;
        let joiner = prepared.agent;
        let inner = TreeKemGroup::from_welcome(&welcome, prepared.identity)
            .map_err(|e| MlsError::Welcome(format!("treekem from_welcome: {e}")))?;

        let mut agent_to_leaf = HashMap::new();
        if let Some(leaf) = inner.own_leaf() {
            agent_to_leaf.insert(joiner, leaf);
        }
        Ok(Self {
            inner,
            agent_to_leaf,
        })
    }

    /// Apply a `Commit` produced by another member (add / remove / rekey).
    ///
    /// # Errors
    /// Returns [`MlsError`] if the commit is malformed or fails verification.
    pub fn process_commit(&mut self, commit: &[u8]) -> Result<()> {
        let commit: TreeKemCommit = decode(commit, "commit")?;
        // Forget any leaves this commit removes (best-effort map maintenance).
        if !commit.removed_leaves.is_empty() {
            let removed: std::collections::HashSet<u32> =
                commit.removed_leaves.iter().copied().collect();
            self.agent_to_leaf.retain(|_, leaf| !removed.contains(leaf));
        }
        self.inner
            .process_commit(&commit)
            .map_err(|e| MlsError::SaorsaMls(format!("treekem process_commit: {e}")))
    }

    /// Produce a `Commit` removing `member` from the group. The caller delivers
    /// it to all remaining members.
    ///
    /// **Resolution caveat (Phase 1/2):** this instance can only resolve agents
    /// it added itself, plus its own leaf — `process_commit` cannot learn the
    /// `AgentId` of members *another* daemon added (the wire `Commit` carries
    /// only `(leaf, KeyPackage)`, no `AgentId`, and the AgentId↔identity binding
    /// is not wired until ADR-0012 Phase 2/4). Drive removal from the
    /// authoritative named-group roster (`src/groups`), which knows every
    /// member's `AgentId`, rather than relying on this instance's best-effort
    /// map.
    ///
    /// # Errors
    /// Returns [`MlsError::MemberNotInGroup`] if the agent's leaf is unknown to
    /// this instance, or [`MlsError`] on TreeKEM failure.
    pub fn remove_member(&mut self, member: AgentId) -> Result<Vec<u8>> {
        let leaf = self.agent_to_leaf.get(&member).copied().ok_or_else(|| {
            MlsError::MemberNotInGroup(format!("unknown leaf for {:?}", member.as_bytes()))
        })?;
        let commit = self
            .inner
            .remove_member(leaf)
            .map_err(|e| MlsError::SaorsaMls(format!("treekem remove_member: {e}")))?;
        self.agent_to_leaf.remove(&member);
        encode(&commit, "commit")
    }

    /// Produce an update `Commit` that rotates this member's key material
    /// (post-compromise healing). Deliver to all members.
    ///
    /// # Errors
    /// Returns [`MlsError`] on TreeKEM failure.
    pub fn update(&mut self) -> Result<Vec<u8>> {
        let commit = self
            .inner
            .update()
            .map_err(|e| MlsError::SaorsaMls(format!("treekem update: {e}")))?;
        encode(&commit, "commit")
    }

    /// Encrypt an application message for the group. Returns encoded
    /// [`ApplicationCiphertext`].
    ///
    /// # Errors
    /// Returns [`MlsError::EncryptionError`] on failure.
    pub fn encrypt_message(&mut self, plaintext: &[u8]) -> Result<Vec<u8>> {
        let ct = self
            .inner
            .encrypt_message(plaintext)
            .map_err(|e| MlsError::EncryptionError(e.to_string()))?;
        encode(&ct, "ciphertext")
    }

    /// Decrypt an application message produced by a group member.
    ///
    /// # Errors
    /// Returns [`MlsError::DecryptionError`] on malformed input or failure.
    pub fn decrypt_message(&mut self, ciphertext: &[u8]) -> Result<Vec<u8>> {
        let ct: ApplicationCiphertext = decode(ciphertext, "ciphertext")
            .map_err(|e| MlsError::DecryptionError(e.to_string()))?;
        self.inner
            .decrypt_message(&ct)
            .map_err(|e| MlsError::DecryptionError(e.to_string()))
    }

    /// The group's current epoch.
    #[must_use]
    pub fn epoch(&self) -> u64 {
        self.inner.epoch()
    }

    /// The group identifier.
    #[must_use]
    pub fn group_id(&self) -> &[u8] {
        self.inner.group_id()
    }

    /// Number of active members.
    #[must_use]
    pub fn member_count(&self) -> u32 {
        self.inner.member_count()
    }

    /// Serialize the full group state for persistence. **Contains private key
    /// material** — the caller MUST protect it at rest (Phase 4 persists it with
    /// the same `0600` model x0x uses for other key files; see ADR-0012).
    ///
    /// # Errors
    /// Returns [`MlsError`] on snapshot/encode failure.
    pub fn to_snapshot_bytes(&self) -> Result<Vec<u8>> {
        self.inner
            .to_snapshot_bytes()
            .map_err(|e| MlsError::MlsOperation(format!("treekem snapshot: {e}")))
    }

    /// Restore a group from a snapshot, re-supplying the member identity.
    ///
    /// Only restorable for a member whose `MemberIdentity` the caller still
    /// holds — i.e. one created via [`Self::prepare_member`] /
    /// [`Self::join_from_welcome`]. A group made with [`Self::create`] cannot be
    /// restored yet, because `create` generates its identity internally and does
    /// not expose it; persisting the owning identity across restarts requires an
    /// upstream saorsa-mls change (`MemberIdentity` `#[serde(skip)]`s its secret
    /// keys) and is tracked in ADR-0012 Phase 4.
    ///
    /// # Errors
    /// Returns [`MlsError`] if the snapshot is malformed or the identity does
    /// not match.
    pub fn from_snapshot_bytes(snapshot: &[u8], prepared: PreparedMember) -> Result<Self> {
        let joiner = prepared.agent;
        let inner = TreeKemGroup::from_snapshot_bytes(snapshot, prepared.identity)
            .map_err(|e| MlsError::MlsOperation(format!("treekem restore: {e}")))?;
        let mut agent_to_leaf = HashMap::new();
        if let Some(leaf) = inner.own_leaf() {
            agent_to_leaf.insert(joiner, leaf);
        }
        Ok(Self {
            inner,
            agent_to_leaf,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn agent(id: u8) -> AgentId {
        let mut bytes = [0u8; 32];
        bytes[0] = id;
        // Vary more than the first byte so distinct agents map to distinct
        // MemberIds even though the bridge only reads the first 16 bytes.
        bytes[1] = id.wrapping_mul(7).wrapping_add(1);
        AgentId(bytes)
    }

    #[test]
    fn create_solo_encrypt_decrypt_roundtrip() {
        let mut g = TreeKemMlsGroup::create(b"room".to_vec(), agent(1)).expect("create");
        assert_eq!(g.epoch(), 0);
        assert_eq!(g.member_count(), 1);
        let ct = g.encrypt_message(b"hello self").expect("encrypt");
        let pt = g.decrypt_message(&ct).expect("decrypt");
        assert_eq!(pt, b"hello self");
    }

    #[test]
    fn cross_instance_join_over_the_wire_then_exchange() {
        // Alice creates; Bob prepares an identity and publishes a key package.
        let alice_id = agent(1);
        let bob_id = agent(2);
        let mut alice =
            TreeKemMlsGroup::create(b"group-A".to_vec(), alice_id).expect("alice create");
        let bob_prepared = TreeKemMlsGroup::prepare_member(bob_id).expect("bob prepare");

        // Everything crosses the boundary as bytes (simulating the wire).
        let kp_bytes = bob_prepared.key_package_bytes().to_vec();
        let out = alice.add_member(bob_id, &kp_bytes).expect("add_member");

        // Bob joins from the Welcome bytes with the identity he prepared.
        let mut bob =
            TreeKemMlsGroup::join_from_welcome(bob_prepared, &out.welcome).expect("bob join");

        // Both at the same post-add epoch with two members.
        assert_eq!(alice.epoch(), bob.epoch(), "epochs must converge");
        assert_eq!(alice.member_count(), 2);
        assert_eq!(bob.member_count(), 2);

        // Alice → Bob: real cross-instance decryption (FS/PCS path).
        let ct = alice
            .encrypt_message(b"welcome to the group")
            .expect("encrypt");
        let pt = bob.decrypt_message(&ct).expect("bob decrypt");
        assert_eq!(pt, b"welcome to the group");

        // Bob → Alice as well.
        let ct2 = bob.encrypt_message(b"glad to be here").expect("encrypt");
        let pt2 = alice.decrypt_message(&ct2).expect("alice decrypt");
        assert_eq!(pt2, b"glad to be here");
    }

    #[test]
    fn wrong_group_message_does_not_decrypt() {
        let mut a = TreeKemMlsGroup::create(b"group-A".to_vec(), agent(1)).expect("a");
        let mut b = TreeKemMlsGroup::create(b"group-B".to_vec(), agent(2)).expect("b");
        let ct = a.encrypt_message(b"secret A").expect("encrypt");
        assert!(
            b.decrypt_message(&ct).is_err(),
            "a group-A ciphertext must not decrypt in group B"
        );
    }

    #[test]
    fn snapshot_with_mismatched_identity_is_rejected_not_panicked() {
        // A group produces a non-empty snapshot, and attempting to restore it
        // with a *different* member's identity is rejected cleanly (no panic).
        // This guards the security property that a snapshot is bound to its
        // owner's identity. NOTE (Phase 4): `create()` does not expose the
        // identity it generates, so a created group cannot yet be restored at
        // all — persisting the owning identity is tracked in ADR-0012 Phase 4.
        let g = TreeKemMlsGroup::create(b"snap".to_vec(), agent(3)).expect("create");
        let snap = g.to_snapshot_bytes().expect("snapshot");
        assert!(!snap.is_empty(), "snapshot must serialize");

        let wrong = TreeKemMlsGroup::prepare_member(agent(4)).expect("prepare other");
        let restored = TreeKemMlsGroup::from_snapshot_bytes(&snap, wrong);
        assert!(
            restored.is_err(),
            "restoring a snapshot with a mismatched identity must fail"
        );
    }

    #[test]
    fn duplicate_add_is_rejected() {
        // Adding the same agent twice must be refused — saorsa-mls would
        // otherwise create a second orphaned leaf for the same agent.
        let mut alice = TreeKemMlsGroup::create(b"g".to_vec(), agent(1)).expect("create");
        let bob_id = agent(2);
        let bob = TreeKemMlsGroup::prepare_member(bob_id).expect("prepare");
        let kp = bob.key_package_bytes().to_vec();
        alice.add_member(bob_id, &kp).expect("first add ok");

        let bob2 = TreeKemMlsGroup::prepare_member(bob_id).expect("prepare again");
        let err = alice
            .add_member(bob_id, bob2.key_package_bytes())
            .unwrap_err();
        assert!(matches!(err, MlsError::MlsOperation(_)));
        assert_eq!(
            alice.member_count(),
            2,
            "duplicate add must not grow the tree"
        );
    }

    #[test]
    fn remove_unknown_member_errors_cleanly() {
        let mut g = TreeKemMlsGroup::create(b"room".to_vec(), agent(1)).expect("create");
        let err = g.remove_member(agent(9)).unwrap_err();
        assert!(matches!(err, MlsError::MemberNotInGroup(_)));
    }
}
